import LegalPageLayout, { LegalSection } from '../components/LegalPageLayout';

export default function TermsOfService() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      lastUpdated="June 1, 2026"
      intro="These Terms of Service govern your access to and use of Sumalyze (located at https://sumalyze.space), including our tools, workspaces, exports, and documentation. By accessing or using the platform, you agree to be bound by these terms."
    >
      <LegalSection title="1. Acceptance of Terms & Account Security">
        <p>
          By creating an account, pasting text, uploading documents, or subscribing to our plans, you represent that you are at least the age of digital consent in your jurisdiction and agree to comply with these Terms. 
        </p>
        <p>
          You are responsible for safeguarding the credentials you use to access the platform. You must immediately notify us at <a href="mailto:support@sumalyze.space" style={{ color: '#ff8fa3', textDecoration: 'underline' }}>support@sumalyze.space</a> if you suspect any security breach or unauthorized usage of your account.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of Service & User Content">
        <p>
          Sumalyze provides an AI communication intelligence workspace offering document parsing, text summarization, key points extraction, tone analysis, action steps extraction, saved history, multi-format exports (Copy, TXT, Markdown, PDF, DOCX), and interactive Agent Mode.
        </p>
        <p>
          <strong>Ownership:</strong> You retain full ownership and intellectual property rights in the text, files, and documents you upload or submit to Sumalyze ("User Content"). 
        </p>
        <p>
          <strong>License to Sumalyze:</strong> You grant us a limited, non-exclusive, worldwide, royalty-free license to host, parse, and transmit your User Content solely to the extent necessary to provide the service (which includes sending inputs securely to our designated AI API processors, such as Google Gemini and OpenRouter).
        </p>
      </LegalSection>

      <LegalSection title="3. Acceptable Use & Prohibited Activities">
        <p>You agree to use Sumalyze in accordance with all local, national, and international laws. Specifically, you agree not to:</p>
        <ul style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 12 }}>
          {[
            'Use the platform for any illegal purpose, or to upload, process, or distribute unlawful or rights-infringing content.',
            'Attempt to scrape, crawl, index, or programmatically extract data or user outputs from the service.',
            'Abuse, bypass, or overload rate limiters, security parameters, or API routers (including executing concurrent automated requests to bypass plan quotas).',
            'Reverse-engineer, decompile, or attempt to extract the source code or proprietary pipelines of the platform.',
            'Transmit viruses, malware, trojan horses, or upload documents containing corrupted files or malicious payloads.',
            'Use the outputs generated by the AI to create deceptive, malicious, or harmful material, or to represent AI-generated text as fully human-authored where disclosure is ethically or legally required.',
            'Violate the terms of service of our sub-processors, payment providers, or hosting hosts.'
          ].map((item, idx) => (
            <li key={idx} style={{ display: 'flex', gap: 10, fontSize: 14, color: 'rgba(255,255,255,0.6)' }}>
              <span style={{ color: '#E23E57', flexShrink: 0 }}>✕</span>
              {item}
            </li>
          ))}
        </ul>
      </LegalSection>

      <LegalSection title="4. Subscription Plans, Billing, & Paddle Checkout">
        <p>
          Sumalyze offers several plans: Free, Starter, Pro, and Max. Detailed limits (including daily/monthly run quotas, file size boundaries, and export availability) are specified on our pricing page. 
        </p>
        <p>
          <strong>No Unlimited Usage:</strong> We do not offer unlimited API requests or processing. All paid and free tiers are subject to rate limits and fair use counters. Exceeding your plan’s limits requires upgrading or waiting for the period to reset.
        </p>
        <p>
          <strong>Paddle Merchant of Record:</strong> All subscription payments, card authorizations, invoices, billing operations, and local tax processing are handled by our Merchant of Record, Paddle. By purchasing a subscription, you authorize recurring charges to your payment method.
        </p>
        <p>
          <strong>Cancellation & Renewals:</strong> Your subscription will automatically renew at the end of each billing cycle (monthly or annual). You can cancel your subscription at any time through your account settings billing portal when available, or by contacting billing support.
        </p>
        <p>
          <strong>Team Workspace:</strong> Access to our Team Workspace is currently waitlist-only and requires manual review and onboarding. Registering on the waitlist does not guarantee approval or access.
        </p>
        <p>
          <strong>Ko-fi Support:</strong> Optional financial support via Ko-fi is a voluntary donation. While we may grant promotional Pro access for a limited time (e.g. 7 days) as a thank-you, Ko-fi donations are not regular subscriptions and do not guarantee permanent paid features.
        </p>
      </LegalSection>

      <LegalSection title="5. AI Disclaimer & Limitation of Warranties">
        <p>
          Sumalyze uses advanced generative AI API integrations to process text. You acknowledge and agree that:
        </p>
        <ul style={{ display: 'flex', flexDirection: 'column', gap: 8, margin: '8px 0 0 16px', listStyleType: 'disc' }}>
          <li>AI models can generate output that is incorrect, incomplete, biased, or misleading.</li>
          <li>Outputs are provided for informational, organization, and draft-generation purposes only. They do not constitute professional, legal, financial, audit, medical, or regulatory compliance advice.</li>
          <li>You are solely responsible for reviewing and validating the accuracy, legality, and suitability of all AI-generated outputs before relying on them.</li>
          <li>The service is provided on an "as is" and "as available" basis, without warranties of any kind.</li>
        </ul>
      </LegalSection>

      <LegalSection title="6. Limitation of Liability">
        <p>
          To the maximum extent permitted by applicable law, Sumalyze, its operators, affiliates, and sub-processors shall not be liable for any indirect, incidental, special, consequential, or punitive damages. This includes, but is not limited to, loss of profits, data corruption, business interruption, or any damages arising from your reliance on AI-generated outputs or system downtime.
        </p>
        <p>
          In no event shall our total aggregate liability for any claims under these Terms exceed the total amount paid by you to Sumalyze in the three (3) months immediately preceding the event giving rise to the claim.
        </p>
      </LegalSection>

      <LegalSection title="7. Suspension & Termination">
        <p>
          We reserve the right to suspend, disable, or terminate your workspace access or account immediately, without prior notice or liability, if we determine in our sole discretion that you have violated these Terms, bypassed API limits, engaged in abuse, or failed to pay subscription dues.
        </p>
      </LegalSection>

      <LegalSection title="8. Modifications to Service & Terms">
        <p>
          We continually update and refine Sumalyze. We reserve the right to add, modify, or discontinue features, plan limits, or subscription pricing at any time. If we make material changes to these Terms of Service, we will notify you by updating the "Last updated" date of this document or via email.
        </p>
      </LegalSection>

      <LegalSection title="9. Contact & Support">
        <p>
          If you have any questions, disputes, or complaints regarding these Terms, please contact support at{' '}
          <a href="mailto:support@sumalyze.space" style={{ color: '#ff8fa3', textDecoration: 'underline' }}>support@sumalyze.space</a>.
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
